[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[plugin]
prepend_preloaders = [
# Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo" },
    { mime = "application/subrip", run = "mediainfo" },
]

prepend_previewers = [
# Replace magick, image, video with mediainfo
    { mime = "{audio,video,image}/*", run = "mediainfo"},
    { mime = "application/subrip", run = "mediainfo" },
# There are more extensions which are supported by mediainfo.
# Just add file's MIME type to `previewers`, `preloaders` above.
# https://mediaarea.net/en/MediaInfo/Support/Formats

# Archive previewer
    { mime = "application/*zip",            run = "ouch" },
    { mime = "application/x-tar",           run = "ouch" },
    { mime = "application/x-bzip2",         run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar",           run = "ouch" },
    { mime = "application/x-xz",            run = "ouch" },
    { mime = "application/xz",              run = "ouch" },
]

