#!/bin/bash

# Hyprland IPC를 통해 창 포커스 이벤트를 구독
socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do
    if [[ "$line" == activewindow\>\>* ]]; then
        app_class=$(echo "$line" | cut -d'>' -f3 | cut -d',' -f1)
        if [[ "$app_class" == "com.moonlight_stream.Moonlight" || "$app_class" == "virt-manager" ]]; then
            hyprctl keyword cursor:hide_on_key_press false
            hyprctl keyword cursor:inactive_timeout 0
        else
            hyprctl keyword cursor:hide_on_key_press true
            hyprctl keyword cursor:inactive_timeout 5
        fi
    fi
done
