#!/bin/bash

source ~/.local/share/wayland-scripts/backend

# This script will helps you without reload your sway program after below codes changed.
# NOTE: If you want remove or declare new variable, please edit exception handling function at below.
# NOTE: `status_command` will not work properly. Please write these settings in configuration file.

function logout() {
    input=$(notify_send --action='1=󰍃' 'Logout' 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.')
    if [[ -n $input && $input -eq 1 ]]; then
        swaymsg exit
    fi
}

function swayidle_init() {
    killall swayidle &> /dev/null
    if [ -n "$1" -a "$1" == "start" ]; then
        swayidle -w \
            timeout 15 'swaymsg "output * power off"; playerctl pause' \
            resume 'swaymsg "output * power on"' &> /dev/null &
    fi
}

function lock_session() {
    local busy=0

    if [ -n "$(pgrep -x swaylock)" ]; then
        debug_message='unable to launch swaylock. swaylock is already running.'
        return $LINENO
    fi

    target_splash=$(change_wallpaper)
    if [ $? -ne 0 ]; then
        debug_message='unable to load swaylock wallpaper. Please check `~/Pictures/Wallpaper-Bank/wallpapers` directory permission.'
        return $LINENO
    fi

    [ -p /run/mouse-control.fifo ] && echo "off" > /run/mouse-control.fifo

    swayidle_init "start"
    if [ -f "$XDG_RUNTIME_DIR/lock-privacy" ]; then
        swaylock -elF --clock -S --effect-blur 7x5 --effect-vignette 0.5:0.5 --grace 5
    else
        swaylock -elF --clock -i "$target_splash" --grace 5
    fi

    if [ -p /run/mouse-control.fifo ]; then
        echo "on" > /run/mouse-control.fifo
        notify_send -t 5000 'Power Manager' 'Please wait until USB Bus is ready.'
    fi

    swayidle_init
}

########    DO NOT CHANGE OR REMOVE BELOW LINES    ########
#   This script will not work after changing below code   #
###########################################################
if [ $# -eq 0 ]; then
    echo "usage: $0 <function [options]>" >&2
    exit 127
else
    "${@}"
    exit_code=$?
    if [ $exit_code -gt 0 ]; then
        source ~/.local/share/wayland-scripts/stack_trace
        gui_error_handler "$exit_code" "$1" "$0" "$debug_message" "${@:2}"
    fi

    exit $exit_code
fi
###########################################################
