#!/bin/bash

swaymsg seat \* hide_cursor when-typing enable
swaymsg seat \* hide_cursor 5000

# Sway IPC를 통해 창 포커스 이벤트를 구독
swaymsg -m -t subscribe '["window"]' | jq --unbuffered -r '.change, .container.app_id' | while read -r event; read -r app_id; do
    # 포커스가 바뀌었을 때 (focus 이벤트)
    if [[ "$event" == "focus" ]]; then
        if [[ "$app_id" == "com.moonlight_stream.Moonlight" ]]; then
            # Moonlight 창으로 들어오면 커서 숨김 해제
            swaymsg seat \* hide_cursor when-typing disable
            swaymsg seat \* hide_cursor 0
        else
            # 다른 창으로 나가면 다시 커서 숨김 활성화 (기본 설정값으로)
            swaymsg seat \* hide_cursor when-typing enable
            swaymsg seat \* hide_cursor 5000
        fi
    fi
done
