#!/bin/sh

### Idle configuration
#
# Example configuration:
#
# exec swayidle -w \
#          timeout 300 'swaylock -efF --clock -i `find $HOME/Pictures/Wallpaper-Bank/wallpapers -type f | shuf -n 1`' \
#          timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
#          timeout 60 'if pgrep -x swaylock; then systemctl suspend-then-hibernate; fi' \
#          before-sleep 'swaylock -efF --clock -i `find $HOME/Pictures/Wallpaper-Bank/wallpapers -type f | shuf -n 1`'
# This will lock your screen after 300 seconds of inactivity, then turn off
# your displays after another 300 seconds, and turn your screens back on when
# resumed. It will also lock your screen before your computer goes to sleep.

killall swayidle &> /dev/null
if [ $1 == "MASKED" ]; then
    exit 1
fi

swayidle -w \
    timeout 15 '\
        if pgrep -x swaylock; then \
            swaymsg "output * power off"; \
            if [[ $(playerctl status 2> /dev/null) == "Playing" ]]; then\
                playerctl pause; \
            fi;\
        fi\
    ' resume 'swaymsg "output * power on"'\
    timeout 180 '\
        if pgrep -x swaylock; then \
            ~/.config/sway/src/backend "enter_sleep";\
        fi\
    ' resume 'swaymsg "output * power on"'
#     ' resume 'swaymsg "output * power on"'\
#     timeout 300 '\
#         if [[ $(playerctl status 2> /dev/null) != "Playing" ]]; then\
#             ~/.config/sway/src/backend "lock_session";\
#         fi\
#     ' resume 'swaymsg "output * power on"'\
#     timeout 315 '\
#         if pgrep -x swaylock; then \
#             swaymsg "output * power off"; \
#         fi\
#     ' resume 'swaymsg "output * power on"'\
#     timeout 600 '\
#         if pgrep -x swaylock; then \
#             ~/.config/sway/src/backend "enter_sleep";\
#         fi\
#     ' resume 'swaymsg "output * power on"'\
#     timeout 1800 '\
#         swaymsg "output * power off"; \
#     ' resume 'swaymsg "output * power on"'

