#!/bin/bash

refresh_interval=30

# NOTE: If you wanna to change weather reports format, please check https://github.com/chubin/wttr.in#one-line-output

lock_file=/tmp/widget-sway-weather.lock
prev_output=/tmp/widget-sway-weather.log
target_url=wttr.in?M\&format="%c+%t+%w+%p+%h\n"
man_url=curl.se/docs/manpage.html

if [ "$1" == "--reload" -o "$1" == "-r" ]; then
    echo 0 > $lock_file
fi

if [ $(cat $lock_file) -eq 0 ]; then
    curl -sf $target_url -w "%{http_code}\n" > $prev_output
    parse_err=$?
    if [ $parse_err -ne 0 ]; then
        return=$(cat $prev_output | tail -n 1)
        [ "$return" != '000' ] && parse_err=$return
        echo "$man_url (-$parse_err)" | tee $prev_output
        exit 1
    elif [ $(cat $prev_output | head -n 1 | grep -cE '^[A-Za-z]') -gt 0 ]; then
        echo "$man_url (-8)" | tee $prev_output
        echo 0 > $lock_file
        exit 1
    else
        cat $prev_output | head -n 1 | sed 's/+//g' | tee $prev_output > /dev/null
        if [ $(cat $prev_output | wc -w) -ne 5 ]; then
            echo "$man_url (-18)" | tee $prev_output
            echo 0 > $lock_file
            exit 1
        fi

        if [ $(cat $prev_output | awk '{ print $4 }' | grep -cE '0\.[0-9]mm') -eq 1 ]; then
            cat $prev_output | awk '{ print $1 " " $2 " " $3 " " $5 }' | tee $prev_output
        else
            cat $prev_output | awk '{ print $1 " " $2 " " $3 " " $4 }' | tee $prev_output
        fi
        date -d '1 hour' +'%s' > $lock_file
    fi
elif [ $(date +'%s') -ge $(cat $lock_file) ]; then
    cat $prev_output
    echo 0 > $lock_file
else
    if [ $(cat $prev_output | tail -n 1 | grep -cE '^[0-9][0-9][0-9]') -ne 0 ]; then
        echo "$man_url (-$(echo $(cat $prev_output | tail -n 1 | grep -cE '^[0-9][0-9][0-9]') | tail -n 1 | grep -cE '^[0-9][0-9][0-9]'))" | tee $prev_output
        echo 0 > $lock_file
    elif [ $(file /tmp/widget-sway-weather.log | grep -c empty) -eq 1 ]; then
        echo "$man_url (-22)" | tee $prev_output
        echo 0 > $lock_file
    else
        if [ $(expr $(date +'%S') % 2) -eq 0 ]; then
            cat $prev_output
        else
            elapsed_time=$(python -c "print(int((1 - ($(cat $lock_file) - $(date +'%s')) / 3600) * 100))" | cut -d. -f1)
            stat -c "%y" $prev_output | cut -d. -f1 | sed "s/^[0-9][0-9][0-9][0-9]-/🗘 $elapsed_time% /"
        fi
    fi
fi
