#!/bin/bash

refresh_interval=30

# NOTE: If you wanna to change weather reports format, please check https://github.com/chubin/wttr.in#one-line-output

lock_file=/tmp/widget-sway-weather.lock
prev_output=/tmp/widget-sway-weather.log
target_url=wttr.in?M\&format="%c+%t+%w+%p+%h\n"
man_url=curl.se/docs/manpage.html

if [ "$1" == "--reload" -o "$1" == "-r" ]; then
    echo 0 > $lock_file
fi

if [ $(cat $lock_file) -eq 0 ]; then
    curl -s $target_url > $prev_output
    parse_err=$?
    if [ $parse_err -ne 0 ]; then
        echo "$man_url (-$parse_err)" | tee $prev_output
        exit 1
    else
        echo 1 > $lock_file
    fi

    if [ "$(cat $prev_output | awk '{ print $4 }')" == '0.0mm' ]; then
        cat $prev_output | awk '{ print $1 " " $2 " " $3 " " $5 }' | tee $prev_output
    else
        cat $prev_output | awk '{ print $1 " " $2 " " $3 " " $4 }' | tee $prev_output
    fi
elif [ $(cat $lock_file) -ge $(expr $refresh_interval \* 60) ]; then
    cat $prev_output
    echo 0 > $lock_file
else
    output=$(cat $prev_output)
    if [ -z "$output" ]; then
        echo "$man_url (-$parse_err)" | tee $prev_output
        echo 0 > $lock_file
    else
        echo $output
        echo $(expr $(cat $lock_file) + 1) > $lock_file
    fi
fi
